name: Release
run-name: Releasing default_project_name

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  is_mirror_repo:
    name: Check if mirror repo
    runs-on: ubuntu-latest
    if: ${{ github.repository != vars.MIRROR_URL }}
    steps:
      - run: echo OK

  release_project:
    name: Release
    needs: [is_mirror_repo]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Auto Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: default_project_name
          prerelease: false
  

  push_docker_image:
    name: Release project in docker
    needs: [is_mirror_repo, release_project]
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: julesdelt/default_project_name

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
